version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: false
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL : mongodb://admin:pass@localhost:8081/db?ssl=false
      ME_CONFIG_MONGODB_ENABLE_ADMIN : true
      ME_CONFIG_MONGODB_AUTH_USERNAME: rootuser
      ME_CONFIG_MONGODB_AUTH_PASSWORD: rootpass
      ME_CONFIG_MONGODB_SERVER: mongodb

volumes:
  data: {}

networks:
  default:
    name: mongodb_network